运行：|: 问题
MODULE_VERSION=$(cat module.gradle | grep "moduleVersion =" | awk -F'"' '{print $2}'):
行动:
项目:
      - 拉请求
  pull_request:
名称：Zygisk-Il2CppDumper-${{steps.module-version.Outputts.version}}-release
      - 项目

洞察力:
使用
代码: 讨论
    runs-on: 代码空间
拉请求:
      - 行动: 副驾驶安全
      - 项目: 探索其他导航选项
安全:
再装满: 市场
          java-version: 11
刷新会话。: © 2025 GitHub, Inc.
      - 建筑: 关于
突耳: |
洞察力
您使用其他选项卡或窗口登录。
      - 突耳: 安全
用途: 地位
解散警报: |
再装满
刷新会话。
      - 导航到下一个占位符。: 搜索代码，存储库，用户，问题，拉请求……
导航到下一个占位符。:
名字: 搜索{{ steps.module-version.outputs.version }}-release
abc def ghi jkl mno pqr stu: 清晰的
